spring.application.name=docmind-AI

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# File Upload
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

server.port=2025

# JWT Configuration
jwt.secret=7E4C4A5A2F8B9C1D3E5F7A9B1C2D4E6F7A8B9C1D3E5F7A9B1C2D4E6F7A8B9C
jwt.expiration=86400000


